### PR TITLE
Halef integration

### PR DESCRIPTION
**Pull request by langep**
I have implemented the necessary changes to use the MRCPv2 implementation within Halef. The changes concern audio playback from URLs and recognition using the approach used inside Halef.

### CODE REVIEW

**Comment by rapgro** [comment]
I guess I'll never understand why to bundle all those 3rdparty binary jars. All of the dependencies could be handled via maven and replaced with individual dependency entries into a pom file for each sub project.

**Comment by rapgro** [comment]
I guess I'll never understand why to bundle all those 3rdparty binary jars. All of the dependencies could be handled via maven and replaced with individual dependency entries into a pom file for each sub project.

**Comment by langep** [comment]
We have done this for the cairo dependencies of the mrcpv2 implementation but it is not yet integrated here.

**Comment by schnelle** [comment]
Merging into head

**Pull request merged**
